run_id: m3-storm-k120
generator:
  duration: 2700.0
  mean_kill: 120.0
  mean_straggle: 300.0
  mean_partition: 400.0
  seed: 7
  replicas: 2
events:
- at: 75.1
  fault: stop
  target: 0
- at: 84.9
  fault: kill_safe
  target: 1
- at: 90.5
  fault: cont
  target: 0
- at: 153.1
  fault: kill_safe
  target: 1
- at: 260.5
  fault: kill_safe
  target: 0
- at: 374.8
  fault: partition
  target: 1
- at: 400.8
  fault: heal
  target: 1
- at: 666.6
  fault: kill_safe
  target: 0
- at: 667.7
  fault: kill_safe
  target: 0
- at: 728.5
  fault: partition
  target: 0
- at: 736.8
  fault: kill_safe
  target: 1
- at: 739.1
  fault: partition
  target: 0
- at: 753.6
  fault: heal
  target: 0
- at: 759.5
  fault: heal
  target: 0
- at: 772.9
  fault: kill_safe
  target: 1
- at: 810.3
  fault: kill_safe
  target: 0
- at: 918.3
  fault: kill_safe
  target: 1
- at: 997.6
  fault: stop
  target: 0
- at: 1024.5
  fault: cont
  target: 0
- at: 1144.4
  fault: kill_safe
  target: 0
- at: 1164.8
  fault: partition
  target: 1
- at: 1171.0
  fault: kill_safe
  target: 1
- at: 1187.3
  fault: heal
  target: 1
- at: 1390.4
  fault: kill_safe
  target: 1
- at: 1522.0
  fault: stop
  target: 1
- at: 1546.8
  fault: cont
  target: 1
- at: 1565.5
  fault: stop
  target: 0
- at: 1585.6
  fault: cont
  target: 0
- at: 1710.2
  fault: partition
  target: 0
- at: 1728.5
  fault: heal
  target: 0
- at: 1767.8
  fault: kill_safe
  target: 0
- at: 1791.5
  fault: kill_safe
  target: 1
- at: 1833.3
  fault: kill_safe
  target: 1
- at: 1842.3
  fault: kill_safe
  target: 1
- at: 1849.5
  fault: kill_safe
  target: 0
- at: 1850.7
  fault: partition
  target: 1
- at: 1889.3
  fault: heal
  target: 1
- at: 1909.9
  fault: stop
  target: 1
- at: 1927.2
  fault: cont
  target: 1
- at: 1942.3
  fault: kill_safe
  target: 1
- at: 1948.1
  fault: stop
  target: 0
- at: 1965.9
  fault: cont
  target: 0
- at: 1968.7
  fault: stop
  target: 0
- at: 1981.7
  fault: cont
  target: 0
- at: 2119.7
  fault: partition
  target: 1
- at: 2138.3
  fault: heal
  target: 1
- at: 2205.8
  fault: kill_safe
  target: 1
- at: 2217.7
  fault: partition
  target: 1
- at: 2230.1
  fault: stop
  target: 0
- at: 2255.9
  fault: heal
  target: 1
- at: 2259.7
  fault: cont
  target: 0
- at: 2268.3
  fault: kill_safe
  target: 1
- at: 2410.0
  fault: kill_safe
  target: 0
- at: 2412.7
  fault: kill_safe
  target: 0
- at: 2442.0
  fault: stop
  target: 0
- at: 2447.9
  fault: kill_safe
  target: 1
- at: 2464.1
  fault: cont
  target: 0
- at: 2508.9
  fault: partition
  target: 0
- at: 2524.1
  fault: kill_safe
  target: 1
- at: 2546.0
  fault: heal
  target: 0
- at: 2691.6
  fault: kill_safe
  target: 0
