run_id: storm-n32
generator:
  duration: 1800.0
  mean_kill: 60.0
  mean_straggle: 240.0
  mean_partition: 300.0
  seed: 7
  replicas: 32
events:
- at: 34.8
  fault: stop
  target: 7
- at: 42.5
  fault: kill_safe
  target: 21
- at: 54.9
  fault: cont
  target: 7
- at: 76.6
  fault: kill_safe
  target: 28
- at: 130.3
  fault: kill_safe
  target: 1
- at: 310.4
  fault: stop
  target: 17
- at: 319.3
  fault: partition
  target: 3
- at: 327.6
  fault: cont
  target: 17
- at: 333.3
  fault: kill_safe
  target: 9
- at: 333.9
  fault: kill_safe
  target: 15
- at: 340.9
  fault: stop
  target: 3
- at: 341.8
  fault: heal
  target: 3
- at: 357.4
  fault: stop
  target: 1
- at: 358.7
  fault: cont
  target: 3
- at: 368.4
  fault: kill_safe
  target: 26
- at: 370.4
  fault: cont
  target: 1
- at: 386.4
  fault: kill_safe
  target: 26
- at: 405.2
  fault: kill_safe
  target: 9
- at: 459.1
  fault: kill_safe
  target: 31
- at: 566.5
  fault: stop
  target: 12
- at: 572.2
  fault: kill_safe
  target: 14
- at: 585.5
  fault: kill_safe
  target: 16
- at: 596.1
  fault: cont
  target: 12
- at: 695.2
  fault: kill_safe
  target: 31
- at: 728.4
  fault: partition
  target: 2
- at: 736.0
  fault: stop
  target: 12
- at: 746.6
  fault: heal
  target: 2
- at: 758.1
  fault: cont
  target: 12
- at: 833.7
  fault: partition
  target: 21
- at: 872.3
  fault: heal
  target: 21
- at: 883.9
  fault: kill_safe
  target: 10
- at: 895.8
  fault: kill_safe
  target: 31
- at: 916.7
  fault: kill_safe
  target: 27
- at: 919.2
  fault: stop
  target: 17
- at: 921.2
  fault: kill_safe
  target: 19
- at: 924.8
  fault: kill_safe
  target: 4
- at: 932.3
  fault: cont
  target: 17
- at: 971.1
  fault: kill_safe
  target: 16
- at: 1035.5
  fault: partition
  target: 30
- at: 1054.1
  fault: heal
  target: 30
- at: 1102.9
  fault: kill_safe
  target: 26
- at: 1109.0
  fault: partition
  target: 18
- at: 1134.2
  fault: kill_safe
  target: 20
- at: 1147.2
  fault: heal
  target: 18
- at: 1205.0
  fault: kill_safe
  target: 12
- at: 1206.3
  fault: kill_safe
  target: 7
- at: 1223.9
  fault: kill_safe
  target: 31
- at: 1262.0
  fault: kill_safe
  target: 22
- at: 1327.3
  fault: partition
  target: 1
- at: 1345.8
  fault: kill_safe
  target: 15
- at: 1364.5
  fault: heal
  target: 1
- at: 1400.1
  fault: kill_safe
  target: 0
- at: 1415.1
  fault: kill_safe
  target: 17
- at: 1474.8
  fault: partition
  target: 5
- at: 1504.1
  fault: heal
  target: 5
- at: 1518.0
  fault: stop
  target: 21
- at: 1532.8
  fault: cont
  target: 21
- at: 1599.6
  fault: kill_safe
  target: 8
- at: 1683.8
  fault: kill_safe
  target: 30
- at: 1727.6
  fault: partition
  target: 31
- at: 1728.1
  fault: stop
  target: 26
- at: 1733.4
  fault: partition
  target: 13
- at: 1748.6
  fault: heal
  target: 31
- at: 1757.4
  fault: cont
  target: 26
- at: 1770.3
  fault: heal
  target: 13
- at: 1788.7
  fault: kill_safe
  target: 27
